apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-extra-resources
parameters:
- name: JUPYTERHUB_NAMESPACE
  value: ""
  required: true
- name: JUPYTERHUB_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${JUPYTERHUB_APPLICATION}-res
    namespace: ${JUPYTERHUB_NAMESPACE}
    labels:
      app: ${JUPYTERHUB_APPLICATION}-${JUPYTERHUB_NAMESPACE}
      spawner: learning-portal
  data:
    extra_resources.json: |-
      {
        "kind": "List",
        "apiVersion": "v1",
        "items": [
          {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
              "name": "percona-xtradb-cluster-operator"
            }
          },
          {
            "kind": "Role",
            "apiVersion": "rbac.authorization.k8s.io/v1beta1",
            "metadata": {
              "name": "percona-xtradb-cluster-operator"
            },
            "rules": [
              {
                "apiGroups": [
                  "pxc.percona.com"
                ],
                "resources": [
                  "perconaxtradbclusters",
                  "perconaxtradbbackups"
                ],
                "verbs": [
                  "get",
                  "list",
                  "watch",
                  "create",
                  "update",
                  "patch",
                  "delete"
                ]
              },
              {
                "apiGroups": [
                  ""
                ],
                "resources": [
                  "pods",
                  "pods/exec",
                  "configmaps",
                  "services",
                  "persistentvolumeclaims",
                  "secrets"
                ],
                "verbs": [
                  "get",
                  "list",
                  "watch",
                  "create",
                  "update",
                  "patch",
                  "delete"
                ]
              },
              {
                "apiGroups": [
                  "apps"
                ],
                "resources": [
                  "deployments",
                  "replicasets",
                  "statefulsets"
                ],
                "verbs": [
                  "get",
                  "list",
                  "watch",
                  "create",
                  "update",
                  "patch",
                  "delete"
                ]
              },
              {
                "apiGroups": [
                  "batch"
                ],
                "resources": [
                  "jobs",
                  "cronjobs"
                ],
                "verbs": [
                  "get",
                  "list",
                  "watch",
                  "create",
                  "update",
                  "patch",
                  "delete"
                ]
              },
              {
                "apiGroups": [
                  "policy"
                ],
                "resources": [
                  "poddisruptionbudgets"
                ],
                "verbs": [
                  "get",
                  "list",
                  "watch",
                  "create",
                  "update",
                  "patch",
                  "delete"
                ]
              }
            ]
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1beta1",
            "metadata": {
              "name": "percona-xtradb-cluster-operator"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "percona-xtradb-cluster-operator"
              }
            ],
            "roleRef": {
              "kind": "Role",
              "name": "percona-xtradb-cluster-operator",
              "apiGroup": "rbac.authorization.k8s.io"
            }
          },
          {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
              "name": "percona-xtradb-cluster-operator"
            },
            "spec": {
              "replicas": 1,
              "selector": {
                "matchLabels": {
                  "name": "percona-xtradb-cluster-operator"
                }
              },
              "template": {
                "metadata": {
                  "labels": {
                    "name": "percona-xtradb-cluster-operator"
                  }
                },
                "spec": {
                  "serviceAccountName": "percona-xtradb-cluster-operator",
                  "containers": [
                    {
                      "name": "percona-xtradb-cluster-operator",
                      "image": "percona/percona-xtradb-cluster-operator:0.3.0",
                      "ports": [
                        {
                          "containerPort": 60000,
                          "name": "metrics"
                        }
                      ],
                      "command": [
                        "percona-xtradb-cluster-operator"
                      ],
                      "imagePullPolicy": "Always",
                      "env": [
                        {
                          "name": "WATCH_NAMESPACE",
                          "valueFrom": {
                            "fieldRef": {
                              "fieldPath": "metadata.namespace"
                            }
                          }
                        },
                        {
                          "name": "OPERATOR_NAME",
                          "value": "percona-xtradb-cluster-operator"
                        }
                      ]
                    }
                  ]
                }
              }
            }
          }
        ]
      }
